version: '3.2'
services:
  backend:
    build: ""
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: mydata
        target: /app/data

  frontend:
    build: ..
    ports:
      - "8080:8080"
volumes:
  mydata: